CREATE TABLE tb_hash (
    id_ int PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,
    campo TEXT)
    PARTITION BY HASH (id_);

CREATE TABLE tb_hash_0
    PARTITION OF tb_hash
    FOR VALUES WITH (MODULUS 5, REMAINDER 0);

CREATE TABLE tb_hash_1
    PARTITION OF tb_hash
    FOR VALUES WITH (MODULUS 5, REMAINDER 1);

CREATE TABLE tb_hash_2
    PARTITION OF tb_hash
    FOR VALUES WITH (MODULUS 5, REMAINDER 2);

CREATE TABLE tb_hash_3
    PARTITION OF tb_hash
    FOR VALUES WITH (MODULUS 5, REMAINDER 3);

CREATE TABLE tb_hash_4
    PARTITION OF tb_hash
    FOR VALUES WITH (MODULUS 5, REMAINDER 4);

INSERT INTO tb_hash (id_, campo)
    SELECT
        generate_series(1, 1000000), -- Um milhão de registros
        sha512((random() * 1000)::text::bytea); -- Geração de texto aletório

