SELECT
    schemaname||'.'||relname AS catalogo
    FROM pg_stat_sys_tables
    WHERE schemaname IN ('pg_catalog', 'information_schema')
    ORDER BY schemaname, relname;

SELECT
    n.nspname||'.'||c.relname AS view_de_sistema
    FROM pg_class AS c
    INNER JOIN pg_namespace AS n
        ON (c.relnamespace = n.oid)
    WHERE n.nspname IN ('pg_catalog', 'information_schema')
    AND c.relkind = 'v'
    ORDER BY random();

CREATE TABLE tb_foo(
    id_ int PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,
    campo1 int2,
    campo2 int4,
    campo3 int8,
    campo4 text);

SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_name = 'tb_foo'
    AND table_schema = 'public';

DROP TABLE tb_foo;
