CREATE TABLE tb_foo(
    id_ int PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,
    campo2 int,
    campo3 int);

INSERT INTO tb_foo (id_, campo2, campo3)
    SELECT
        generate_series(1, 1000000),
        (random() * 1000000)::int,
        (random() * 1000000)::int;

EXPLAIN ANALYZE
    SELECT id_
        FROM tb_foo
        WHERE (campo2 BETWEEN 235 AND 587)
            AND campo3 = 1000;

DROP TABLE tb_foo;

