CREATE TABLE tb_foo(
    id_ int PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,
    numero int,
    texto text);

INSERT INTO tb_foo (numero, texto)
    SELECT (random() * 1000000)::int,
    substr(md5(generate_series(1, 2000000)::text), 1, 7);

CREATE INDEX idx_teste ON tb_foo (numero, id_);

EXPLAIN ANALYZE
SELECT
    numero, id_
    FROM tb_foo
    WHERE numero > 25000
    ORDER BY numero, id_ LIMIT 20;

EXPLAIN ANALYZE
SELECT
    numero, id_, texto
    FROM tb_foo
    WHERE numero > 25000
    ORDER BY numero, id_ LIMIT 20;

CREATE INDEX idx_teste2 on tb_foo (numero, id_, texto);

EXPLAIN ANALYZE
SELECT
    numero, id_, texto
    FROM tb_foo
    WHERE numero > 25000
    ORDER BY numero, id_ LIMIT 20;

