CREATE TEMP TABLE tb_foo(
    id_ int PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,
    cor text);

INSERT INTO tb_foo (cor) VALUES
    ('Laranja'),
    ('Preto'),
    ('Branco'),
    ('Azul'),
    ('Amarelo'),
    ('Vermelho'),
    ('Verde'),
    ('Cinza');

TABLE tb_foo;

UPDATE tb_foo SET cor = 'Vinho' WHERE id_ = 6;

\d tb_foo

CLUSTER tb_foo USING tb_foo_pkey;

DROP TABLE tb_foo;

