CREATE TEMP TABLE tb_foo(
    id_ int PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,
    campo1 int,
    campo2 text);

CREATE INDEX idx_1 ON tb_foo (campo1);
CREATE INDEX idx_2 ON tb_foo (campo2);

INSERT INTO tb_foo (id_, campo1, campo2)
SELECT
    generate_series(1, 1000000),
    (random() * 10000)::int,
    md5((random() * 10000)::text);

EXPLAIN ANALYZE
SELECT campo2 FROM tb_foo
    WHERE id_ BETWEEN 5 AND 20000;

EXPLAIN ANALYZE
SELECT campo2 FROM tb_foo
    WHERE campo1 BETWEEN 5 AND 20000;

SELECT
    indexrelname, relname, idx_scan, idx_tup_read, idx_tup_fetch
    FROM pg_stat_user_indexes;

DROP INDEX idx_2;

DROP TABLE tb_foo;

