CREATE TABLE tb_foo(
    id_ int PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,
    numero int,
    texto text);

INSERT INTO tb_foo (numero, texto)
    SELECT (random() * 1000000)::int,
    substr(md5(generate_series(1, 2000000)::text), 1, 7);

CREATE VIEW vw_foo AS
    SELECT numero, texto
        FROM tb_foo
        WHERE id_ % 2 = 0;

CREATE MATERIALIZED VIEW mv_foo AS
    SELECT numero, texto
        FROM tb_foo
        WHERE id_ % 2 = 0;

SELECT count(*) FROM mv_foo;

INSERT INTO tb_foo (numero, texto)
    SELECT (random() * 1000000)::int,
    substr(md5(generate_series(1, 1000000)::text), 1, 7);

SELECT count(*) FROM vw_foo;
SELECT count(*) FROM mv_foo;

REFRESH MATERIALIZED VIEW mv_foo;

EXPLAIN ANALYZE
SELECT numero, texto FROM vw_foo;

EXPLAIN ANALYZE
SELECT numero, texto FROM mv_foo;
